/**
 * VS Code extension host for codegraph.
 * The Activity Bar icon (and codegraph.open) opens a WebviewPanel with the
 * canvas; parsing runs in the host only after the user picks a root on the
 * start screen (or via Parse Folder… / rebuild). The last parsed graph is cached
 * for the session so closing and reopening the panel replays it without a
 * re-parse. The on-canvas editor is backed by the real VS Code document: it is
 * opened via openTextDocument, unsaved edits are mirrored live through a
 * WorkspaceEdit (making the file dirty without saving), Save persists to disk,
 * and native-editor changes sync back to the canvas. All file paths resolve
 * against the parsed graph root (not the workspace folder).
 */
import * as vscode from "vscode";
import * as path from "node:path";
import * as fs from "node:fs";
import { Worker } from "node:worker_threads";
import { getMessages } from "../i18n/webview.js";
// Precompiled Pug template for the canvas (generated by scripts/esbuild.mjs).
import renderWebview from "./generated/webview-template.cjs";

type HostToWebview =
  | { type: "graph"; graph: unknown }
  | { type: "busy"; busy: boolean }
  | { type: "progress"; text: string }
  | { type: "fileContent"; path: string; text: string; language: string }
  | { type: "saved"; path: string }
  | { type: "error"; message: string }
  | { type: "externalChange"; path: string; text: string };

/** Coarse parse progress streamed by the worker (mirrors core ParseProgress). */
type ParseProgress = { phase: "discover" | "parse"; files: number; parsed?: number };

type WebviewToHost =
  | { type: "ready" }
  | { type: "openFile"; path: string }
  | { type: "editFile"; path: string; text: string }
  | { type: "saveFile"; path: string; text: string }
  | { type: "rebuild"; root?: string; includeTests?: boolean }
  | { type: "pickFolder" };

let currentPanel: vscode.WebviewPanel | undefined;
let pendingRoot: string | undefined;
/**
 * Last successfully parsed graph and its root, cached for the session so that
 * closing and reopening the panel replays it instead of forcing a re-parse.
 * Survives panel disposal; cleared only on extension deactivate.
 */
let lastGraph: unknown | undefined;
let lastRoot: string | undefined;
/** cancels the in-flight parse when a newer one starts or the user cancels */
let activeParseCts: vscode.CancellationTokenSource | undefined;
/** paths open in overlays (relative), used for externalChange notifications */
const openOverlayPaths = new Set<string>();
/**
 * The last document text the host and canvas are known to agree on, keyed by
 * relative path — set whenever the host reads (openFile), writes (editFile /
 * saveFile), or forwards a genuine external change. A document change whose text
 * still equals this value is the host's own edit (or a no-op reconcile), never a
 * real external change, so it is not echoed back to the canvas. Unlike a one-shot
 * flag this survives duplicate/late change events and the debounce window, so a
 * canvas that is briefly ahead of the last sync is never mislabeled "changed
 * externally". Cleared when the panel is disposed.
 */
const syncedText = new Map<string, string>();
/** Diagnostic log for parses (root/selfDir, counts, opt-in per-path trace). */
let output: vscode.OutputChannel | undefined;

/** Appends a timestamped line to the "Codegraph Studio" output channel. */
function log(line: string): void {
  output?.appendLine(`${new Date().toISOString()}  ${line}`);
}

/** Marker rejection for a parse that was cancelled (user or superseded). */
class ParseCancelled extends Error {}

/**
 * Extension entry point: registers commands, the Activity Bar launch view, and
 * forwards on-disk saves of overlay-open files back to the webview.
 * Why: the webview mirrors files in in-canvas editors, so external saves must be
 * pushed to it to keep the overlays in sync. The launch view is an empty
 * webview that immediately opens the canvas panel and closes the sidebar —
 * Activity Bar containers require a view, but we don't want a side menu.
 */
export function activate(context: vscode.ExtensionContext): void {
  output = vscode.window.createOutputChannel("Codegraph Studio");
  context.subscriptions.push(output);

  context.subscriptions.push(
    vscode.commands.registerCommand("codegraph.open", () => openPanel(context)),
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("codegraph.rebuild", () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (currentPanel && folder) {
        currentPanel.reveal(vscode.ViewColumn.One);
        void sendGraph(currentPanel, folder.uri.fsPath, context);
      } else {
        // No panel yet: open it and parse the workspace as soon as it is ready
        // (pendingRoot drives the ready handler; without it the start screen waits).
        if (folder) pendingRoot = folder.uri.fsPath;
        openPanel(context);
      }
    }),
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("codegraph.rebuildFrom", async () => {
      const root = await pickFolderRoot();
      if (!root) return;
      if (currentPanel) {
        currentPanel.reveal(vscode.ViewColumn.One);
        void sendGraph(currentPanel, root, context);
      } else {
        pendingRoot = root;
        openPanel(context);
      }
    }),
  );

  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider(
      "codegraph.launch",
      new LaunchViewProvider(context),
    ),
  );

  // Mirror edits made in a *native* VS Code editor of an overlay-open file back
  // onto the canvas (both while typing and on save), so the two stay in sync.
  // Echoes of the host's own writes are filtered out via `hostWrites`.
  context.subscriptions.push(
    vscode.workspace.onDidChangeTextDocument((e) => pushDocToCanvas(e.document)),
    vscode.workspace.onDidSaveTextDocument((doc) => pushDocToCanvas(doc)),
  );
}

/**
 * Path of `doc` relative to the active graph root (the parsed folder, else the
 * first workspace folder), in POSIX form — or undefined if it lies outside.
 * Why: overlay paths are relative to the parsed root, which may differ from the
 * workspace folder, so sync must resolve against the same base the graph used.
 */
function relForActiveRoot(doc: vscode.TextDocument): string | undefined {
  const base = lastRoot ?? vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (!base) return undefined;
  const rel = path.relative(base, doc.uri.fsPath).split(path.sep).join("/");
  if (!rel || rel.startsWith("../") || path.isAbsolute(rel)) return undefined;
  return rel;
}

/**
 * Pushes a document's current text to the canvas overlay for its path, unless it
 * is not open in an overlay or the change is merely the echo of a host write.
 */
function pushDocToCanvas(doc: vscode.TextDocument): void {
  if (!currentPanel) return;
  const rel = relForActiveRoot(doc);
  if (!rel || !openOverlayPaths.has(rel)) return;
  const text = doc.getText();
  // equal to the last host↔canvas sync → our own write or a no-op, not external
  if (syncedText.get(rel) === text) return;
  syncedText.set(rel, text); // now the agreed text is this external content
  post(currentPanel, { type: "externalChange", path: rel, text });
}

/**
 * Empty Activity Bar view: when it appears, open the canvas panel and collapse
 * the sidebar so the icon feels like a direct launch into the graph.
 */
class LaunchViewProvider implements vscode.WebviewViewProvider {
  constructor(private readonly context: vscode.ExtensionContext) {}

  resolveWebviewView(webviewView: vscode.WebviewView): void {
    webviewView.webview.html = "";
    const launch = (): void => {
      openPanel(this.context);
      void vscode.commands.executeCommand("workbench.action.closeSidebar");
    };
    launch();
    webviewView.onDidChangeVisibility(() => {
      if (webviewView.visible) launch();
    });
  }
}

/** Folder picker shared by Parse Folder… and the canvas "Choose folder" button. */
async function pickFolderRoot(): Promise<string | undefined> {
  const picked = await vscode.window.showOpenDialog({
    canSelectFolders: true,
    canSelectFiles: false,
    canSelectMany: false,
    openLabel: vscode.l10n.t("Parse folder"),
  });
  return picked?.[0]?.fsPath;
}

/**
 * Extension teardown: clears panel and overlay state.
 * Why: prevents stale references when the extension is deactivated/reloaded.
 */
export function deactivate(): void {
  activeParseCts?.cancel();
  activeParseCts = undefined;
  currentPanel = undefined;
  lastGraph = undefined;
  lastRoot = undefined;
  openOverlayPaths.clear();
  syncedText.clear();
}

/**
 * Sends a typed message from the host to the webview.
 * Why: single choke point for the host→webview protocol.
 */
function post(panel: vscode.WebviewPanel, msg: HostToWebview): void {
  panel.webview.postMessage(msg);
}

/**
 * Opens (or reveals) the single codegraph panel and wires up its messaging.
 * Why: reuses one panel per session, requires an open workspace folder, and
 * applies a strict CSP with a per-panel nonce for the webview scripts.
 */
function openPanel(context: vscode.ExtensionContext): void {
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) {
    vscode.window.showErrorMessage(
      vscode.l10n.t("Codegraph Studio: open a project folder (File → Open Folder)."),
    );
    return;
  }

  if (currentPanel) {
    // Reveal only — parsing starts from the start-screen buttons, rebuild
    // commands, or a pendingRoot left by Parse Folder… / Reparse Workspace.
    currentPanel.reveal(vscode.ViewColumn.One);
    return;
  }

  const panel = vscode.window.createWebviewPanel(
    "codegraph",
    "Codegraph Studio",
    vscode.ViewColumn.One,
    {
      enableScripts: true,
      retainContextWhenHidden: true,
      localResourceRoots: [
        vscode.Uri.file(path.join(context.extensionPath, "dist", "webview")),
      ],
    },
  );
  currentPanel = panel;

  const nonce = randomNonce();
  panel.webview.html = getHtml(panel.webview, context.extensionPath, nonce);

  panel.onDidDispose(
    () => {
      activeParseCts?.cancel();
      activeParseCts = undefined;
      currentPanel = undefined;
      openOverlayPaths.clear();
      syncedText.clear();
    },
    null,
    context.subscriptions,
  );

  panel.webview.onDidReceiveMessage(
    async (raw: WebviewToHost) => {
      try {
        await handleMessage(panel, context, folder, raw);
      } catch (e) {
        const message = e instanceof Error ? e.message : String(e);
        post(panel, { type: "error", message });
      }
    },
    null,
    context.subscriptions,
  );
}

/**
 * Dispatches an incoming webview→host message
 * (ready/rebuild/pickFolder/openFile/saveFile).
 * Why: centralizes the request handling; reads go through workspace.fs and
 * writes through a WorkspaceEdit so VS Code's undo/dirty tracking is respected.
 */
async function handleMessage(
  panel: vscode.WebviewPanel,
  context: vscode.ExtensionContext,
  folder: vscode.WorkspaceFolder,
  msg: WebviewToHost,
): Promise<void> {
  if (!msg || typeof msg !== "object" || !("type" in msg)) return;

  if (msg.type === "ready") {
    // Parse only when a command already chose a root (Parse Folder… / Reparse).
    if (pendingRoot) {
      const root = pendingRoot;
      pendingRoot = undefined;
      void sendGraph(panel, root, context);
      return;
    }
    // Otherwise replay the last parse from this session so reopening the panel
    // doesn't force a re-parse; only a first-ever open shows the start screen.
    if (lastGraph !== undefined) {
      log(`replaying cached graph for root=${lastRoot ?? "?"}`);
      post(panel, { type: "graph", graph: lastGraph });
    }
    return;
  }

  if (msg.type === "rebuild") {
    const root = (msg.root || "").trim() || folder.uri.fsPath;
    if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) {
      post(panel, {
        type: "error",
        message: vscode.l10n.t("path not found or not a folder: {0}", root),
      });
      return;
    }
    void sendGraph(panel, root, context, !!msg.includeTests);
    return;
  }

  if (msg.type === "pickFolder") {
    const root = await pickFolderRoot();
    if (!root) return;
    void sendGraph(panel, root, context);
    return;
  }

  // File paths resolve against the parsed graph root, NOT the workspace folder —
  // parsing an arbitrary folder must still read/write its real files.
  const rootUri = lastRoot ? vscode.Uri.file(lastRoot) : folder.uri;

  if (msg.type === "openFile") {
    const rel = normalizeRel(msg.path);
    const uri = vscode.Uri.joinPath(rootUri, ...rel.split("/"));
    let text: string;
    try {
      // openTextDocument (not fs.readFile) so any *unsaved* edits already live in
      // VS Code's model are shown on the canvas too.
      const doc = await vscode.workspace.openTextDocument(uri);
      text = doc.getText();
    } catch {
      post(panel, { type: "error", message: vscode.l10n.t("could not read {0}", rel) });
      return;
    }
    openOverlayPaths.add(rel);
    syncedText.set(rel, text); // canvas and host start in agreement
    const language = rel.endsWith(".tsx") ? "tsx" : rel.endsWith(".ts") ? "typescript" : "javascript";
    post(panel, { type: "fileContent", path: rel, text, language });
    return;
  }

  // Live (unsaved) edit: mirror the canvas text into the real document so VS Code
  // marks the file dirty and shows it everywhere — but do NOT save it to disk.
  if (msg.type === "editFile") {
    const rel = normalizeRel(msg.path);
    const uri = vscode.Uri.joinPath(rootUri, ...rel.split("/"));
    try {
      const doc = await vscode.workspace.openTextDocument(uri);
      const text = msg.text ?? "";
      syncedText.set(rel, text); // canvas is authoritative for this text now
      if (doc.getText() === text) return; // already in sync — no churn, no echo
      const full = new vscode.Range(doc.positionAt(0), doc.positionAt(doc.getText().length));
      const edit = new vscode.WorkspaceEdit();
      edit.replace(uri, full, text);
      await vscode.workspace.applyEdit(edit);
    } catch {
      /* file vanished/renamed — ignore; a later save surfaces the error */
    }
    return;
  }

  if (msg.type === "saveFile") {
    const rel = normalizeRel(msg.path);
    const uri = vscode.Uri.joinPath(rootUri, ...rel.split("/"));
    const doc = await vscode.workspace.openTextDocument(uri);
    const text = msg.text ?? "";
    syncedText.set(rel, text);
    if (doc.getText() !== text) {
      const full = new vscode.Range(doc.positionAt(0), doc.positionAt(doc.getText().length));
      const edit = new vscode.WorkspaceEdit();
      edit.replace(uri, full, text);
      const ok = await vscode.workspace.applyEdit(edit);
      if (!ok) {
        post(panel, { type: "error", message: vscode.l10n.t("could not apply edit: {0}", rel) });
        return;
      }
    }
    await doc.save();
    post(panel, { type: "saved", path: rel });
    return;
  }
}

/**
 * Builds the graph for `root` in a worker and posts it to the webview (or an
 * error). Why: parsing is CPU-bound and runs off the host event loop so the
 * editor stays responsive; a Notification progress spinner marks the work and
 * lets the user cancel it, and a `busy` message drives the canvas overlay.
 * A newer parse supersedes an older one (its worker is terminated), so only the
 * latest result reaches the webview.
 */
async function sendGraph(
  panel: vscode.WebviewPanel,
  root: string,
  context: vscode.ExtensionContext,
  includeTests = false,
): Promise<void> {
  activeParseCts?.cancel();
  const cts = new vscode.CancellationTokenSource();
  activeParseCts = cts;

  // Verbose per-path tracing is opt-in; root/selfDir/counts are always logged.
  const debug = vscode.workspace.getConfiguration("codegraph").get<boolean>("debugParsePaths", false);
  log(`parse start: root=${root} selfDir=${context.extensionPath} includeTests=${includeTests} debugParsePaths=${debug}`);

  post(panel, { type: "busy", busy: true });
  try {
    const graph = await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        cancellable: true,
        title: vscode.l10n.t("Codegraph Studio: analyzing {0}…", root),
      },
      (progress, progressToken) => {
        progressToken.onCancellationRequested(() => cts.cancel());
        return parseInWorker(
          context,
          root,
          includeTests,
          cts.token,
          (p) => {
            // Same concise status to both surfaces: the Notification message and
            // the canvas overlay label — so a slow parse never looks hung.
            const text = progressText(p);
            progress.report({ message: text });
            post(panel, { type: "progress", text });
          },
          debug,
          (paths) => {
            for (const p of paths) output?.appendLine(p);
          },
        );
      },
    );
    logGraphCounts(graph);
    // cache for the session so a closed/reopened panel replays without re-parsing
    lastGraph = graph;
    lastRoot = root;
    post(panel, { type: "graph", graph });
  } catch (e) {
    // A cancelled or superseded parse leaves the current graph in place.
    if (e instanceof ParseCancelled) {
      log("parse cancelled/superseded");
    } else {
      const message = e instanceof Error ? e.message : String(e);
      log(`parse error: ${message}`);
      post(panel, { type: "error", message: vscode.l10n.t("parsing: {0}", message) });
    }
  } finally {
    // Only the latest parse clears the busy state; a superseding parse keeps the
    // overlay up until it finishes on its own.
    if (activeParseCts === cts) {
      activeParseCts = undefined;
      cts.dispose();
      post(panel, { type: "busy", busy: false });
    }
  }
}

/**
 * Runs buildGraph in a worker thread, resolving with the graph or rejecting.
 * Why: keeps the synchronous AST walk off the host event loop; cancellation
 * terminates the worker so a long parse never pins a CPU after it is abandoned.
 */
function parseInWorker(
  context: vscode.ExtensionContext,
  root: string,
  includeTests: boolean,
  token: vscode.CancellationToken,
  onProgress?: (p: ParseProgress) => void,
  debug = false,
  onDebug?: (paths: string[]) => void,
): Promise<unknown> {
  return new Promise<unknown>((resolve, reject) => {
    const workerPath = path.join(context.extensionPath, "dist", "parse-worker.cjs");
    const worker = new Worker(workerPath);
    let settled = false;
    const finish = (fn: () => void): void => {
      if (settled) return;
      settled = true;
      sub.dispose();
      void worker.terminate();
      fn();
    };
    const sub = token.onCancellationRequested(() => finish(() => reject(new ParseCancelled())));
    worker.on(
      "message",
      (
        msg: { type?: string; ok?: boolean; graph?: unknown; error?: string; paths?: string[] } &
          Partial<ParseProgress>,
      ) => {
        // Progress and debug traces stream before the single final reply; they
        // never settle the promise.
        if (msg && msg.type === "progress") {
          if (!settled) onProgress?.({ phase: msg.phase!, files: msg.files!, parsed: msg.parsed });
          return;
        }
        if (msg && msg.type === "debug") {
          if (!settled && msg.paths) onDebug?.(msg.paths);
          return;
        }
        finish(() => {
          if (msg && msg.ok) resolve(msg.graph);
          else reject(new Error(msg?.error || "parse failed"));
        });
      },
    );
    worker.on("error", (err) => finish(() => reject(err)));
    worker.on("exit", (code) => {
      if (settled) return;
      finish(() => reject(new Error(`parse worker exited with code ${code}`)));
    });
    worker.postMessage({ root, includeTests, selfDir: context.extensionPath, debug });
  });
}

/** Logs the final file/node/edge counts of a completed parse. */
function logGraphCounts(graph: unknown): void {
  const stats = (graph as { stats?: { files: number; nodes: number; edges: number } })?.stats;
  if (stats) log(`parse done: ${stats.files} files, ${stats.nodes} nodes, ${stats.edges} edges`);
  else log("parse done");
}

/**
 * Formats a coarse {@link ParseProgress} into a localized, one-line status.
 * Why: both the Notification message and the canvas overlay show the same text,
 * so a long parse reads as alive (file counts), not frozen.
 */
function progressText(p: ParseProgress): string {
  if (p.phase === "parse" && typeof p.parsed === "number") {
    return vscode.l10n.t("parsing {0}/{1} files…", p.parsed, p.files);
  }
  return vscode.l10n.t("found {0} files…", p.files);
}

/**
 * Normalizes a webview-supplied path to a clean relative POSIX path.
 * Why: defends against backslashes and leading slashes before joining onto the
 * workspace folder URI.
 */
function normalizeRel(p: string): string {
  return String(p || "")
    .replace(/\\/g, "/")
    .replace(/^\/+/, "");
}

/**
 * Generates a 32-char alphanumeric nonce for the webview CSP.
 * Why: a fresh nonce per panel lets us allow only our own inline scripts.
 */
function randomNonce(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let s = "";
  for (let i = 0; i < 32; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

/**
 * Renders the webview HTML from the precompiled Pug template with a strict CSP.
 * Why: asset URLs must be rewritten via asWebviewUri and locked to the nonce so
 * the panel loads only trusted local resources.
 */
function getHtml(webview: vscode.Webview, extensionPath: string, nonce: string): string {
  const base = path.join(extensionPath, "dist", "webview");
  const asUri = (f: string) => webview.asWebviewUri(vscode.Uri.file(path.join(base, f))).toString();
  const csp = [
    `default-src 'none'`,
    `img-src ${webview.cspSource} data:`,
    `style-src ${webview.cspSource} 'unsafe-inline'`,
    `font-src ${webview.cspSource} data:`,
    `script-src 'nonce-${nonce}'`,
    // same-origin only: lets DevTools fetch our bundles' source maps in dev
    `connect-src ${webview.cspSource}`,
  ].join("; ");

  // follow the VS Code display language; falls back to English
  const lang = vscode.env.language || "en";
  return renderWebview({
    standalone: false,
    csp,
    nonce,
    cssHref: asUri("styles.css"),
    viewerSrc: asUri("viewer.js"),
    editorSrc: asUri("editor.js"),
    t: getMessages(lang),
    lang,
  });
}
